name: Jest Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '38 22 * * 2'
    
jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm cus its faster :)
        run: npm install -g pnpm

      - name: Install all dependencies
        run: pnpm i

      - name: Run Jest Tests
        run: pnpm test
