name: Jest Tests
on: [pull_request, push]
jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install all dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test
